#
# [ Database Configuration Section ]
#
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/OHDSI
    username: ohdsi_admin_user
    password: admin1
    platform: POSTGRESQL
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 9095

#
# [ Other Configuration Attributes ]
#